# -*- coding: utf-8 -*-
"""genai

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14lgY8Ut7wDAHzu4cGPJkshxDpfmpUdog
"""



"""sadfgbhjn fewrgtyujtgrfeds"""

geethika rao kalakonda



"""geethika rao kalakonda"""

a=10
b=20
c=a+b
c

!pip install google-generativeai

import os
import google.generativeai as genai
api_key="AIzaSyC3zzf3X9vvEpbptE0IrBGGV0HS955WG2o"
genai.configure(api_key=api_key)

for m in genai.list_models():
  print(m.name)

"""#text model:Gemini - pro"""

model=genai.GenerativeModel("gemini-pro")
model

response=model.generate_content("List of top 5 indian cricketers")
print(response.text)

import google.generativeai as genai
api_key="AIzaSyC3zzf3X9vvEpbptE0IrBGGV0HS955WG2o"
genai.configure(api_key=api_key)
model=genai.GenerativeModel("gemini-pro")
response=model.generate_content("List of top 5 indian cricketers")
print(response.text)

"""Image model"""

from PIL import Image

img=Image.open("/WhatsApp Image 2024-03-20 at 7.08.41 PM.jpeg")
img

import google.generativeai as genai
api_key="AIzaSyC3zzf3X9vvEpbptE0IrBGGV0HS955WG2o"
genai.configure(api_key=api_key)
model=genai.GenerativeModel("gemini-1.0-pro-vision-latest")
prompt="what are the object in the given image"
response=model.generate_content([prompt,img])
print(response.text)

!pip install streamlit
!npm install localtunel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# from PIL import Image
# api_key="AIzaSyC3zzf3X9vvEpbptE0IrBGGV0HS955WG2o"
# genai.configure(api_key=api_key)
# st.header("Image analytics")
# uploaded_file=st.file_uploader("upload a image",type=["png","jpg","jpeg"])
# if uploaded_file is not None:
#   st.image(Image.open(uploaded_file))
# prompt=st.text_input("Enter the text")
# if st.button("GET RESPONSE"):
#   img=Image.open(uploaded_file)
#   model=genai.GenerativeModel("gemini-1.0-pro-vision-latest")
#   response=model.generate_content([prompt,img])
#   st.markdown(response.text)

!streamlit run /content/app.py & npx localtunnel --port 8501 & curl ipv4.icanhazip.com